### ISSUE TITLE
When I create a daily repeating task (ie: take vitamins) it creates like 30 tasks, instead of just the 1 task for that day.

### ISSUE THREAD

**Issue by ghost** [jsdev2015/recgtasks#39] opened 2018-01-08 13:02 UTC
I just want the task "Take vitamins today" to appear on the top of my default task list every day. Instead, like 3 weeks of the same task appears all at once. Is there any way to stop this from happening?

To reiterate: I check my task list every day. I just want the tasks due on that day to appear on each day. I don't want all the future tasks for weeks to appear on my list!

Thanks!

**Comment by sovcik** [comment] 2018-01-08 13:58
Duplicate of Issue #36

**Closed as completed by sovcik** 2018-01-08 13:58 UTC
