### ISSUE TITLE
Sliding past tasks stopped working?

### ISSUE THREAD

**Issue by dsl101** [jsdev2015/recgtasks#50] opened 2019-03-28 19:56 UTC
Past tasks are no longer sliding to today. Log shows they are processed (not in detail), but they stay stuck on the original date. This started a couple of days ago. I reinstalled, but no joy. Running on Vivaldi 2.4.1488.33. Has been working for many months prior to this week.

```
*** Log beginning ***
Thu Mar 28 19:44:52 GMT 2019 INFO: [C] Removing 2.0 triggers for "processRecurrentLists"
Thu Mar 28 19:44:53 GMT 2019 INFO: [C] No trigger for "processRecurrentLists" found. Installing trigger for time zone GMT.
Thu Mar 28 19:44:54 GMT 2019 INFO: [I] Ignoring task list "Main" - it is not RTTL.
Thu Mar 28 19:44:54 GMT 2019 INFO: [I] Processing RTTL "~Recurring" to list "Main"
Thu Mar 28 19:44:54 GMT 2019 INFO: [I] Fetching tasks for deduplication 
Thu Mar 28 19:44:55 GMT 2019 INFO: [I] Removing possible duplicates for 18.0 task instances.
Thu Mar 28 19:44:55 GMT 2019 INFO: [I] Saving newly created instances of tasks.
Thu Mar 28 19:44:55 GMT 2019 INFO: [I] Sliding past due tasks to date: Thu Mar 28 00:00:00 GMT+00:00 2019
Thu Mar 28 19:44:55 GMT 2019 INFO: [I] Removing duplicate tasks from date: Thu Mar 28 19:44:55 GMT+00:00 2019
Thu Mar 28 19:44:55 GMT 2019 INFO: [C] *** Script execution completed ***
*** Log end ***
```
![image](https://user-images.githubusercontent.com/900542/55188472-65b65000-5193-11e9-919a-bd50cf64b110.png)

**Comment by sovcik** [comment] 2019-04-03 12:40
Hi, sorry for late reply.

Well, not sure what happened yet - most likely some change on Google side
caused by introduction of recurring tasks by Google.
At least I noticed today that I'm able to create recurring tasks in Google
Tasks app on my phone.
My app will soon become obsolete :-)
As for this issue - going to investigate.

J.

**Comment by dsl101** [comment] 2019-04-03 13:06
Right. There's nothing 'repeatable' in the quick task creation in google calendar, but I see you can get to it (eventually) using the panel on the right of calendar. I'm happy to move over to that rather than you spend time on this unless you want to. recgtasks has been really useful for a long time—to the point where even google realise it :).

Of course, I don't suppose they will do sliding overdue tasks any time soon, so if that can be fixed, there's still some value...

**Comment by sovcik** [comment] 2019-04-03 13:21
I noticed it in their mobile app. You are right - standard calendar allows only specifying date AND time.

**Comment by sovcik** [comment] 2019-04-03 13:26
I was just checking why it is not working... well... very strange... "old tasks" which script refused to move are ignored, but if you create new task, then it slids... I also found out that it is enough to move historical task by one day and since then it is recognized by the script...

So as a workaround: move your old task by one day manually in Calendar and then try running recurrent tasks manually from the main app page http://www.recgtasks.com/app (there is a big button for manual run).

And let me know if it worked.  I assume that it will work thereafter...

**Comment by dsl101** [comment] 2019-04-03 13:37
Sadly, I'm not seeing the same. Tasks from 2 days ago moved to 1 day ago still stay at 1 day ago, and a brand new task created for 'April 1st' is still at April 1st...

Could the script print any more logging in the sliding process, to show what tasks it's considering?

**Comment by sovcik** [comment] 2019-04-03 13:38
Yes, you can set it to log "developer level info"

**Comment by dsl101** [comment] 2019-04-03 13:43
Ah, I didn't see that. But it doesn't add much in my case:

```
Wed Apr 03 13:39:47 GMT 2019 INFO: [I] Sliding past due tasks to date: Wed Apr 03 00:00:00 GMT+00:00 2019
Wed Apr 03 13:39:47 GMT 2019 INFO: [D] >> Getting list of overdue tasks: 2019-04-02T23:59:59.000Z
Wed Apr 03 13:39:47 GMT 2019 INFO: [O] >> Slid 0.0 tasks
```

![image](https://user-images.githubusercontent.com/900542/55483555-b825bf80-561e-11e9-8242-fa0fdd150177.png)

'new task' is the one I just created a few moments ago...

**Comment by sovcik** [comment] 2019-04-03 13:48
Even stranger.... I checked using Google tasks API "explorer" https://developers.google.com/tasks/v1/reference/tasks/list and it was interesting that their API returned past tasks having due date set to "today"...

**Comment by sovcik** [comment] 2019-04-03 13:50
You can try it yoursellf all you need is to enter task list ID (look for something like this in your log file)
`Wed Apr 03 13:13:22 GMT 2019 INFO: [D] Settings: {"destTaskListId":"MTgwODQ4MTg1gzY0MjM0MjQwMjg6MDow"`
And set completed and deleted to "Off"

**Comment by sovcik** [comment] 2019-04-03 13:51
And if you are on it, then let me know what is the due date for your Past "new task" :-)

**Comment by sovcik** [comment] 2019-04-03 13:51
I mean, what Google returned to you using that page

**Comment by dsl101** [comment] 2019-04-03 13:57
Looks like a bug in their API:
```
  {
   "kind": "tasks#task",
   "id": "MDg2MjY4MDQwNzYwNDk2MTgxMjI6MDozNTQ2OTU5OTAxNTg0NzA4",
   "etag": "\"84_7Cubo3y98GMV9bE3zQclHxhc/LTIwNTc0NDUyODI\"",
   "title": "new task",
   "updated": "2019-04-03T13:36:09.000Z",
   "selfLink": "https://www.googleapis.com/tasks/v1/lists/MDg2MjY4MDQwNzYwNDk2MTgxMjI6MDow/tasks/MDg2MjY4MDQwNzYwNDk2MTgxMjI6MDozNTQ2OTU5OTAxNTg0NzA4",
   "position": "00000000000001840567",
   "status": "needsAction",
   "due": "2019-04-03T00:00:00.000Z"
  },
```

**Comment by dsl101** [comment] 2019-04-03 13:59
Or, your script _has_ updated the `due` property, but that's not where google is getting the info from in calendar?

**Comment by dsl101** [comment] 2019-04-03 14:01
In fact, here's a 'clean' run:

1. Creating a task in the past
2. Running the google API
3. Running the task sliding
4. Re-running the google API:

before:
```
  {
   "kind": "tasks#task",
   "id": "MDg2MjY4MDQwNzYwNDk2MTgxMjI6MDozNTc1NTE5NjI1NjUwNjU1",
   "etag": "\"84_7Cubo3y98GMV9bE3zQclHxhc/LTEwMDM1MTQzMTY\"",
   "title": "clean new task",
   "updated": "2019-04-03T13:59:33.000Z",
   "selfLink": "https://www.googleapis.com/tasks/v1/lists/MDg2MjY4MDQwNzYwNDk2MTgxMjI6MDow/tasks/MDg2MjY4MDQwNzYwNDk2MTgxMjI6MDozNTc1NTE5NjI1NjUwNjU1",
   "position": "00000000000001839976",
   "status": "needsAction",
   "due": "2019-04-01T00:00:00.000Z"
  },
```

and after:
```
  {
   "kind": "tasks#task",
   "id": "MDg2MjY4MDQwNzYwNDk2MTgxMjI6MDozNTc1NTE5NjI1NjUwNjU1",
   "etag": "\"84_7Cubo3y98GMV9bE3zQclHxhc/LTE4MTI4NjA5NDI\"",
   "title": "clean new task",
   "updated": "2019-04-03T14:00:10.000Z",
   "selfLink": "https://www.googleapis.com/tasks/v1/lists/MDg2MjY4MDQwNzYwNDk2MTgxMjI6MDow/tasks/MDg2MjY4MDQwNzYwNDk2MTgxMjI6MDozNTc1NTE5NjI1NjUwNjU1",
   "position": "00000000000001839976",
   "status": "needsAction",
   "due": "2019-04-03T00:00:00.000Z"
  },
```

So the due date _is_ being updated correctly by your script, but google is ignoring it...

**Comment by sovcik** [comment] 2019-04-03 14:09
I did similar test, but that worked. Will try few more repetitions. Maybe
they are rolling out an update and my calendar was already updated.
Thanks for help.
But it looks there is not much I can do :-(
Sorry.

**Comment by dsl101** [comment] 2019-04-03 14:28
No problem. Thanks for looking. I'll keep trying :).

**Comment by sovcik** [comment] 2019-04-08 06:14
There is a bug report on Google Tasks related to this issue. Seems like a Google issue...
https://issuetracker.google.com/issues/129591245

**Comment by dsl101** [comment] 2019-06-27 13:29
Has anything changed on this? I've noticed that some recently created tasks _are_ now sliding along each day. Some older ones haven't, but maybe there's been a fix Google haven't mentioned?

**Comment by sovcik** [comment] 2019-06-27 14:49
Thanks for reminder.
Yes, there was a fix from Google and it started working again. If you slide those older ones manually they should start sliding too.
Closing this issue for now.

**Comment by dsl101** [comment] 2019-06-28 08:54
Hmm. Not sure if this is premature, but I've found tasks will slide _once_, but then not again when the clock rolls round again. I have a number of tasks which I put on, say, today, but would like them to keep rolling forward until they're marked complete. I use them as reminders but they don't really have a due date that's fixed. But now they move 1 day, then stay there...

**Comment by dsl101** [comment] 2019-06-30 10:59
And, in fact, it seems they slide to _yesterday_. So all my tasks from the week now show as due yesterday (Saturday), and presumably tomorrow they will show as due Sunday, etc. Perhaps to do with the time the task is due, not just the date? Or when the update task runs?

**Comment by sovcik** [comment] 2019-06-30 16:28
I noticed the same behavior too. Not sure why it is happening like that.
Need to investigate.

**Comment by dsl101** [comment] 2019-07-18 12:27
I tested creating a task due in the past, one for 'today', and one due in the future. After the first 24 hours, the task due in the past was moved to 'today' as expected. The one originally set for 'today' moved once to be one day behind. And the one set in the future never moved, even when 'today' went past its due date. All very confusing.

I did also get one of those 'Google Script Error' emails—first time I've seen one for this script. It did not appear to have any significant detail in it though.

**Comment by dsl101** [comment] 2019-07-22 09:25
Now nothing moves again—it worked (almost) for a few days, but now old tasks, moved old tasks, and newly created ones seem to just stay where they were... :(

**Comment by dsl101** [comment] 2019-09-03 09:47
Is this a lost cause now? Really hoping it can be resurrected...

**Comment by sovcik** [comment] 2020-03-26 11:08
Google dueMax issue https://issuetracker.google.com/issues/152429780

**Comment by sovcik** [comment] 2020-03-26 11:09
@dsl101 sorry for looong delay

**Comment by sovcik** [comment] 2020-03-26 11:16
This should be fixed now.

**Closed as completed by sovcik** 2020-03-26 11:16 UTC
